import type { SimpleIcon } from "simple-icons";
import {
  siAnthropic,
  siAsana,
  siAirtable,
  siBox,
  siCalendly,
  siClickup,
  siDiscord,
  siDocker,
  siDropbox,
  siElasticsearch,
  siGithub,
  siGitlab,
  siGmail,
  siGooglebigquery,
  siGooglecalendar,
  siGooglechat,
  siGoogledrive,
  siGooglesheets,
  siGooglemeet,
  siHubspot,
  siIntercom,
  siJira,
  siKubernetes,
  siLinear,
  siMailchimp,
  siMake,
  siMercadopago,
  siMeta,
  siMongodb,
  siMysql,
  siN8n,
  siNotion,
  siOpenai,
  siPaypal,
  siPostgresql,
  siQuickbooks,
  siRedis,
  siSalesforce,
  siSap,
  siSendgrid,
  siShopify,
  siSlack,
  siSnowflake,
  siStripe,
  siTelegram,
  siTwilio,
  siTrello,
  siTypeform,
  siWhatsapp,
  siWoocommerce,
  siZendesk,
  siZapier,
  siZoom,
  siZoho,
} from "simple-icons";

/** Icono vectorial por clave de integración (simple-icons, CC0). */
export const INTEGRATION_SIMPLE_ICONS: Record<string, SimpleIcon> = {
  gmail: siGmail,
  slack: siSlack,
  /** `siMicrosoftteams` ya no existe en simple-icons ≥14; Meet como sustituto visual de “reunión”. */
  teams: siGooglemeet,
  salesforce: siSalesforce,
  hubspot: siHubspot,
  sheets: siGooglesheets,
  stripe: siStripe,
  zendesk: siZendesk,
  twilio: siTwilio,
  mercadopago: siMercadopago,
  facturae: siSap,
  webhook: siZapier,
  inbox: siGmail,
  whatsapp: siWhatsapp,
  discord: siDiscord,
  telegram: siTelegram,
  meta: siMeta,
  notion: siNotion,
  airtable: siAirtable,
  googledrive: siGoogledrive,
  googlecalendar: siGooglecalendar,
  googlechat: siGooglechat,
  jira: siJira,
  linear: siLinear,
  trello: siTrello,
  asana: siAsana,
  clickup: siClickup,
  github: siGithub,
  gitlab: siGitlab,
  docker: siDocker,
  kubernetes: siKubernetes,
  n8n: siN8n,
  make: siMake,
  mongodb: siMongodb,
  postgresql: siPostgresql,
  mysql: siMysql,
  redis: siRedis,
  snowflake: siSnowflake,
  bigquery: siGooglebigquery,
  elasticsearch: siElasticsearch,
  dropbox: siDropbox,
  box: siBox,
  paypal: siPaypal,
  shopify: siShopify,
  woocommerce: siWoocommerce,
  mailchimp: siMailchimp,
  sendgrid: siSendgrid,
  zoho: siZoho,
  calendly: siCalendly,
  typeform: siTypeform,
  quickbooks: siQuickbooks,
  zoom: siZoom,
  intercom: siIntercom,
  openai: siOpenai,
  anthropic: siAnthropic,
};

export function getIntegrationSimpleIcon(key: string): SimpleIcon | null {
  return INTEGRATION_SIMPLE_ICONS[key] ?? null;
}
