import {
  Boxes,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  CircleDollarSign,
  Cloud,
  Code2,
  Database,
  FileSpreadsheet,
  FolderOpen,
  Kanban,
  Layers,
  LayoutGrid,
  Mail,
  Headphones,
  MessageCircle,
  Network,
  Phone,
  Rocket,
  ScanLine,
  Sparkles,
  Store,
  TabletSmartphone,
  Video,
  Zap,
} from "lucide-react";
import type { IntegrationDef } from "@/lib/workflow-data";
import { INTEGRATION_CATALOG } from "@/lib/workflow-data";

/** Listado amplio solo para la landing (no altera la pizarra de flujos). */
const LANDING_EXTRA: IntegrationDef[] = [
  { key: "whatsapp", name: "WhatsApp", Icon: MessageCircle },
  { key: "discord", name: "Discord", Icon: TabletSmartphone },
  { key: "telegram", name: "Telegram", Icon: Phone },
  { key: "meta", name: "Meta / Instagram", Icon: Sparkles },
  { key: "notion", name: "Notion", Icon: LayoutGrid },
  { key: "airtable", name: "Airtable", Icon: FileSpreadsheet },
  { key: "googledrive", name: "Google Drive", Icon: FolderOpen },
  { key: "googlecalendar", name: "Google Calendar", Icon: Calendar },
  { key: "googlechat", name: "Google Chat", Icon: MessageCircle },
  { key: "jira", name: "Jira", Icon: Kanban },
  { key: "linear", name: "Linear", Icon: Rocket },
  { key: "trello", name: "Trello", Icon: LayoutGrid },
  { key: "asana", name: "Asana", Icon: Calendar },
  { key: "clickup", name: "ClickUp", Icon: Layers },
  { key: "github", name: "GitHub", Icon: Code2 },
  { key: "gitlab", name: "GitLab", Icon: Code2 },
  { key: "docker", name: "Docker", Icon: Boxes },
  { key: "kubernetes", name: "Kubernetes", Icon: Network },
  { key: "n8n", name: "n8n", Icon: Zap },
  { key: "make", name: "Make (Integromat)", Icon: Zap },
  { key: "mongodb", name: "MongoDB", Icon: Database },
  { key: "postgresql", name: "PostgreSQL", Icon: Database },
  { key: "mysql", name: "MySQL", Icon: Database },
  { key: "redis", name: "Redis", Icon: Database },
  { key: "snowflake", name: "Snowflake", Icon: Cloud },
  { key: "bigquery", name: "BigQuery", Icon: Cloud },
  { key: "elasticsearch", name: "Elasticsearch", Icon: ScanLine },
  { key: "dropbox", name: "Dropbox", Icon: Cloud },
  { key: "box", name: "Box", Icon: Boxes },
  { key: "paypal", name: "PayPal", Icon: CircleDollarSign },
  { key: "shopify", name: "Shopify", Icon: Store },
  { key: "woocommerce", name: "WooCommerce", Icon: Store },
  { key: "mailchimp", name: "Mailchimp", Icon: Mail },
  { key: "intercom", name: "Intercom", Icon: Headphones },
  { key: "sendgrid", name: "SendGrid", Icon: Mail },
  { key: "zoho", name: "Zoho", Icon: Building2 },
  { key: "calendly", name: "Calendly", Icon: Calendar },
  { key: "typeform", name: "Typeform", Icon: TabletSmartphone },
  { key: "quickbooks", name: "QuickBooks", Icon: Briefcase },
  { key: "zoom", name: "Zoom", Icon: Video },
  { key: "linkedin", name: "LinkedIn", Icon: Briefcase },
  { key: "outlook365", name: "Microsoft 365", Icon: Mail },
  { key: "openai", name: "OpenAI", Icon: Brain },
  { key: "anthropic", name: "Anthropic / Claude", Icon: Sparkles },
];

export const LANDING_INTEGRATIONS: IntegrationDef[] = [
  ...INTEGRATION_CATALOG,
  ...LANDING_EXTRA,
];
